name: mattofalltrades
description: Matt of all trades...
avatar: https://avatars2.githubusercontent.com/u/1879850?s=400&u=83c9db9211c9ffdd60a23c6ac6e490355bc88402&v=4

theme: jekyll-theme-hacker
lsi: false
safe: true
source: docs
incremental: false
highlighter: rouge
gist:
  noscript: false

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
  math_engine: mathjax

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: nfaction
  instagram:
  linkedin: matthew-deporter
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: spikebyte
  stackoverflow: users/14539203/spikebyte # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: nfaction # channel/<your_long_string> or user/<user-name>

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
